### PR TITLE
Linked your imports to a valid CDN

### PR DESCRIPTION
**Pull request by hippyaki**
Removed the script tag as well, which is to be used in index.html

### CODE REVIEW

**Review by hippyaki — COMMENTED** [review]
Go through this updated change. I did it 4 hours back, before replying on forum.

**Comment by meshtiwa** [comment]
> Go through this updated change. I did it 4 hours back, before replying on forum.

**Comment by meshtiwa** [comment]
> Go through this updated change. I did it 4 hours back, before replying on forum.

I went through the updated change and it still does not work.

**Comment by hippyaki** [comment]
> 
> 
> > Go through this updated change. I did it 4 hours back, before replying on forum.
> 
> I went through the updated change and it still does not work.

Drop the public URL, I'll inspect what's going wrong. 

Possibly, keeping the three.min.js locally would serve best for static pages. But let's see.

**Comment by meshtiwa** [comment]
> > > Go through this updated change. I did it 4 hours back, before replying on forum.
> > 
> > 
> > I went through the updated change and it still does not work.
> 
> Drop the public URL, I'll inspect what's going wrong. Update: Found it.
> 
> Possibly, keeping the three.min.js locally would serve best for static pages. But let's see.

Sounds good. Do you still want me to drop the public URL?

**Comment by hippyaki** [comment]
Isn't this what you're trying to implement?

Screenshot (1693)

**Comment by hippyaki** [comment]
There are few more changes in the orbitcontrol.js file. I'll make that and drop the link to the repo.

I hope you can wait for 7-8 hours. I'll make the changes tomorrow morning. (1:00 AM IST over here)

**Comment by meshtiwa** [comment]
> Isn't this what you're trying to implement?
> 
> Screenshot (1693)

Yup! That is exactly what I am trying to get!

**Comment by meshtiwa** [comment]
> There are few more changes in the orbitcontrol.js file. I'll make that and drop the link to the repo.
> 
> I hope you can wait for 7-8 hours. I'll make the changes tomorrow morning. (1:00 AM IST over here)
> 
> Amazing work btw.

Thank you :) And also, no rush. I really appreciate your help!

**Comment by hippyaki** [comment]
https://github.com/hippyaki/Animesh-Port 

You can access the repository from here. There are no errors as of now.

Even though OrbitControls is difficult to import into a static page. Let me know of the features on your localhost so that I can help bring them up over here.

**Comment by hippyaki** [comment]
Do download the whole repository. I'll delete the repository in 24 hours.

**Comment by meshtiwa** [comment]
> Do download the whole repository. I'll delete the repository in 24 hours.

Thank you so much! I actually just realized I only used OrbitControls for testing out a feature that I didn't want in the end, so it is of no use to me.

**Comment by hippyaki** [comment]
In that case, remove the orbit control files as well as the script tag in index.html.

**Pull request closed without merging**
